/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BeginForgotPassword } from '../models';
import { BeginForgotPasswordResponse } from '../models';
import { CompleteForgotPassword } from '../models';
import { CompleteForgotPasswordResponse } from '../models';
import { ProblemDetails } from '../models';
import { VerifyOTPForgotPassword } from '../models';
import { VerifyOTPForgotPasswordResponse } from '../models';
/**
 * ForgotPasswordApi - axios parameter creator
 * @export
 */
export const ForgotPasswordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {BeginForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordBegin: async (body?: BeginForgotPassword, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/forgot-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CompleteForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordComplete: async (body?: CompleteForgotPassword, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/forgot-password/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerifyOTPForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordVerifyOTP: async (body?: VerifyOTPForgotPassword, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/forgot-password/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ForgotPasswordApi - functional programming interface
 * @export
 */
export const ForgotPasswordApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {BeginForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPasswordBegin(body?: BeginForgotPassword, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BeginForgotPasswordResponse>> {
            const localVarAxiosArgs = await ForgotPasswordApiAxiosParamCreator(configuration).forgotPasswordBegin(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {CompleteForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPasswordComplete(body?: CompleteForgotPassword, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompleteForgotPasswordResponse>> {
            const localVarAxiosArgs = await ForgotPasswordApiAxiosParamCreator(configuration).forgotPasswordComplete(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {VerifyOTPForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async forgotPasswordVerifyOTP(body?: VerifyOTPForgotPassword, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerifyOTPForgotPasswordResponse>> {
            const localVarAxiosArgs = await ForgotPasswordApiAxiosParamCreator(configuration).forgotPasswordVerifyOTP(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ForgotPasswordApi - factory interface
 * @export
 */
export const ForgotPasswordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {BeginForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordBegin(body?: BeginForgotPassword, options?: any): AxiosPromise<BeginForgotPasswordResponse> {
            return ForgotPasswordApiFp(configuration).forgotPasswordBegin(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CompleteForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordComplete(body?: CompleteForgotPassword, options?: any): AxiosPromise<CompleteForgotPasswordResponse> {
            return ForgotPasswordApiFp(configuration).forgotPasswordComplete(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VerifyOTPForgotPassword} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        forgotPasswordVerifyOTP(body?: VerifyOTPForgotPassword, options?: any): AxiosPromise<VerifyOTPForgotPasswordResponse> {
            return ForgotPasswordApiFp(configuration).forgotPasswordVerifyOTP(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ForgotPasswordApi - object-oriented interface
 * @export
 * @class ForgotPasswordApi
 * @extends {BaseAPI}
 */
export class ForgotPasswordApi extends BaseAPI {
    /**
     * 
     * @param {BeginForgotPassword} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ForgotPasswordApi
     */
    public forgotPasswordBegin(body?: BeginForgotPassword, options?: any) {
        return ForgotPasswordApiFp(this.configuration).forgotPasswordBegin(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {CompleteForgotPassword} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ForgotPasswordApi
     */
    public forgotPasswordComplete(body?: CompleteForgotPassword, options?: any) {
        return ForgotPasswordApiFp(this.configuration).forgotPasswordComplete(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {VerifyOTPForgotPassword} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ForgotPasswordApi
     */
    public forgotPasswordVerifyOTP(body?: VerifyOTPForgotPassword, options?: any) {
        return ForgotPasswordApiFp(this.configuration).forgotPasswordVerifyOTP(body, options).then((request) => request(this.axios, this.basePath));
    }
}
