/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetUserTodosResponse } from '../models';
import { ProblemDetails } from '../models';
import { SetTodoEntryCompletion } from '../models';
import { SetTodoEntryCompletionResponse } from '../models';
/**
 * TodoApiApi - axios parameter creator
 * @export
 */
export const TodoApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTodos: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/todo/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {SetTodoEntryCompletion} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setTodoEntryCompletion: async (id: string, body?: SetTodoEntryCompletion, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling setTodoEntryCompletion.');
            }
            const localVarPath = `/todo/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodoApiApi - functional programming interface
 * @export
 */
export const TodoApiApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserTodos(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserTodosResponse>> {
            const localVarAxiosArgs = await TodoApiApiAxiosParamCreator(configuration).getUserTodos(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {SetTodoEntryCompletion} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setTodoEntryCompletion(id: string, body?: SetTodoEntryCompletion, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetTodoEntryCompletionResponse>> {
            const localVarAxiosArgs = await TodoApiApiAxiosParamCreator(configuration).setTodoEntryCompletion(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TodoApiApi - factory interface
 * @export
 */
export const TodoApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserTodos(options?: any): AxiosPromise<GetUserTodosResponse> {
            return TodoApiApiFp(configuration).getUserTodos(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {SetTodoEntryCompletion} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setTodoEntryCompletion(id: string, body?: SetTodoEntryCompletion, options?: any): AxiosPromise<SetTodoEntryCompletionResponse> {
            return TodoApiApiFp(configuration).setTodoEntryCompletion(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodoApiApi - object-oriented interface
 * @export
 * @class TodoApiApi
 * @extends {BaseAPI}
 */
export class TodoApiApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiApi
     */
    public getUserTodos(options?: any) {
        return TodoApiApiFp(this.configuration).getUserTodos(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} id 
     * @param {SetTodoEntryCompletion} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiApi
     */
    public setTodoEntryCompletion(id: string, body?: SetTodoEntryCompletion, options?: any) {
        return TodoApiApiFp(this.configuration).setTodoEntryCompletion(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}
