/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountDetail
 */
export interface AccountDetail {
    /**
     * 
     * @type {string}
     * @memberof AccountDetail
     */
    cardId?: any | null;
    /**
     * 
     * @type {AccountConfig}
     * @memberof AccountDetail
     */
    config?: any;
    /**
     * 
     * @type {Array&lt;TransactionSummary&gt;}
     * @memberof AccountDetail
     */
    recentTransactions?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDetail
     */
    id?: any | null;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    createdAt?: any;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    start?: any;
    /**
     * 
     * @type {AccountType}
     * @memberof AccountDetail
     */
    accType?: any;
    /**
     * 
     * @type {string}
     * @memberof AccountDetail
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AccountDetail
     */
    currency?: any | null;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    interest?: any;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    end?: any;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    balance?: any;
    /**
     * 
     * @type {number}
     * @memberof AccountDetail
     */
    target?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AccountDetail
     */
    active?: any;
}
