/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccountCreationRequest
 */
export interface AccountCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    cardId: any;
    /**
     * 
     * @type {number}
     * @memberof AccountCreationRequest
     */
    start: any;
    /**
     * 
     * @type {string}
     * @memberof AccountCreationRequest
     */
    currency: any;
    /**
     * 
     * @type {AccountType}
     * @memberof AccountCreationRequest
     */
    accType: any;
    /**
     * 
     * @type {AccountGoalConfig}
     * @memberof AccountCreationRequest
     */
    goalConfig?: any;
    /**
     * 
     * @type {AccountChallengeConfig}
     * @memberof AccountCreationRequest
     */
    challengeConfig?: any;
    /**
     * 
     * @type {AccountInvestmentConfig}
     * @memberof AccountCreationRequest
     */
    investmentConfig?: any;
    /**
     * 
     * @type {AccountStashConfig}
     * @memberof AccountCreationRequest
     */
    stashConfig?: any;
}
