/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AddCardRequest
 */
export interface AddCardRequest {
    /**
     * 
     * @type {string}
     * @memberof AddCardRequest
     */
    cardNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AddCardRequest
     */
    cvv?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AddCardRequest
     */
    expMonth?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AddCardRequest
     */
    expYear?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AddCardRequest
     */
    country?: any | null;
}
