/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    bankId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    bankName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    ownerId?: any;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    accountHolderName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    hash?: any | null;
}
