/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BlogPost
 */
export interface BlogPost {
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    id?: any | null;
    /**
     * 
     * @type {number}
     * @memberof BlogPost
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof BlogPost
     */
    start?: any;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    url?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    title?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    description?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    imgUrl?: any | null;
    /**
     * 
     * @type {string}
     * @memberof BlogPost
     */
    category?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof BlogPost
     */
    isFeatured?: any;
    /**
     * 
     * @type {Array&lt;BlogComment&gt;}
     * @memberof BlogPost
     */
    comments?: any | null;
    /**
     * 
     * @type {Array&lt;BlogLike&gt;}
     * @memberof BlogPost
     */
    likes?: any | null;
    /**
     * 
     * @type {Array&lt;BlogRead&gt;}
     * @memberof BlogPost
     */
    reads?: any | null;
}
