/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Card
 */
export interface Card {
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    ownerId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    first6?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    last4?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    expiryMonth?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    expiryYear?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof Card
     */
    verified?: any;
    /**
     * 
     * @type {string}
     * @memberof Card
     */
    cardType?: any | null;
}
