/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Challenge
 */
export interface Challenge {
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    fundsInvested?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    description?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Challenge
     */
    imageUrl?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Challenge
     */
    incomePercentage?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Challenge
     */
    active?: any;
    /**
     * 
     * @type {number}
     * @memberof Challenge
     */
    start?: any;
    /**
     * 
     * @type {number}
     * @memberof Challenge
     */
    created?: any;
    /**
     * 
     * @type {Array&lt;ChallengeConfig&gt;}
     * @memberof Challenge
     */
    configs?: any | null;
}
