/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FlutterwaveWebhookData
 */
export interface FlutterwaveWebhookData {
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    txRef?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    flwRef?: any | null;
    /**
     * 
     * @type {number}
     * @memberof FlutterwaveWebhookData
     */
    amount?: any;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    currency?: any | null;
    /**
     * 
     * @type {number}
     * @memberof FlutterwaveWebhookData
     */
    chargedAmount?: any;
    /**
     * 
     * @type {number}
     * @memberof FlutterwaveWebhookData
     */
    appFee?: any;
    /**
     * 
     * @type {number}
     * @memberof FlutterwaveWebhookData
     */
    merchantFee?: any;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    narration?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    status?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlutterwaveWebhookData
     */
    createdAt?: any | null;
    /**
     * 
     * @type {number}
     * @memberof FlutterwaveWebhookData
     */
    accountId?: any;
    /**
     * 
     * @type {FlutterwaveCustomer}
     * @memberof FlutterwaveWebhookData
     */
    customer?: any;
    /**
     * 
     * @type {Card}
     * @memberof FlutterwaveWebhookData
     */
    card?: any;
}
