/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Identity
 */
export interface Identity {
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    id?: any | null;
    /**
     * 
     * @type {Array&lt;RecoveryAddress&gt;}
     * @memberof Identity
     */
    recoveryAddresses?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    schemaId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Identity
     */
    schemaUrl?: any | null;
    /**
     * 
     * @type {Traits}
     * @memberof Identity
     */
    traits?: any;
    /**
     * 
     * @type {Array&lt;VerifiableAddress&gt;}
     * @memberof Identity
     */
    verifiableAddresses?: any | null;
}
