/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InvestmentByIdResponse
 */
export interface InvestmentByIdResponse {
    /**
     * 
     * @type {string}
     * @memberof InvestmentByIdResponse
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof InvestmentByIdResponse
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof InvestmentByIdResponse
     */
    text?: any | null;
    /**
     * 
     * @type {number}
     * @memberof InvestmentByIdResponse
     */
    interest?: any;
    /**
     * 
     * @type {boolean}
     * @memberof InvestmentByIdResponse
     */
    active?: any;
    /**
     * 
     * @type {number}
     * @memberof InvestmentByIdResponse
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof InvestmentByIdResponse
     */
    maturityDate?: any;
    /**
     * 
     * @type {string}
     * @memberof InvestmentByIdResponse
     */
    imageUrl?: any | null;
}
