/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LegalDocument
 */
export interface LegalDocument {
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    slug?: any | null;
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    fileUrl?: any | null;
    /**
     * 
     * @type {number}
     * @memberof LegalDocument
     */
    created?: any;
    /**
     * 
     * @type {string}
     * @memberof LegalDocument
     */
    description?: any | null;
}
