/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Overview
 */
export interface Overview {
    /**
     * 
     * @type {Money}
     * @memberof Overview
     */
    netWorth?: any;
    /**
     * 
     * @type {number}
     * @memberof Overview
     */
    savingsProgress?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Overview
     */
    savingsBreakdown?: any | null;
}
