/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PortfolioAnalyticsResponse
 */
export interface PortfolioAnalyticsResponse {
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalOpenAccounts?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalGoalAccounts?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalChallengeAccounts?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalStashAccounts?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalInvestmentAccounts?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalTransactionsPast7DaysTransactions?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalDeposits7DaysTransactions?: any;
    /**
     * 
     * @type {number}
     * @memberof PortfolioAnalyticsResponse
     */
    totalWithdrawals7DaysTransactions?: any;
}
