/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    type?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    title?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetails
     */
    status?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: any | null;
    /**
     * 
     * @type {{ [key, string]: any;}}
     * @memberof ProblemDetails
     */
    extensions?: any | null;
}
