/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * 
     * @type {boolean}
     * @memberof Session
     */
    active?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    authenticatedAt?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    expiresAt?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    id?: any | null;
    /**
     * 
     * @type {Identity}
     * @memberof Session
     */
    identity?: any;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    issuedAt?: any | null;
}
