/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TodoCriteria
 */
export interface TodoCriteria {
    /**
     * 
     * @type {string}
     * @memberof TodoCriteria
     */
    id?: any | null;
    /**
     * 
     * @type {number}
     * @memberof TodoCriteria
     */
    minAge?: any;
    /**
     * 
     * @type {number}
     * @memberof TodoCriteria
     */
    maxAge?: any;
    /**
     * 
     * @type {string}
     * @memberof TodoCriteria
     */
    monthlyEarnings?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TodoCriteria
     */
    maritalStatus?: any | null;
    /**
     * 
     * @type {number}
     * @memberof TodoCriteria
     */
    minNumKids?: any;
    /**
     * 
     * @type {number}
     * @memberof TodoCriteria
     */
    maxNumKids?: any;
    /**
     * 
     * @type {string}
     * @memberof TodoCriteria
     */
    residenceType?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TodoCriteria
     */
    todoTemplateId?: any | null;
}
