/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TodoAdminData
 */
export interface TodoAdminData {
    /**
     * 
     * @type {string}
     * @memberof TodoAdminData
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TodoAdminData
     */
    text?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof TodoAdminData
     */
    active?: any;
    /**
     * 
     * @type {number}
     * @memberof TodoAdminData
     */
    assigned?: any;
    /**
     * 
     * @type {number}
     * @memberof TodoAdminData
     */
    completed?: any;
    /**
     * 
     * @type {TodoCriteria}
     * @memberof TodoAdminData
     */
    criteria?: any;
    /**
     * 
     * @type {number}
     * @memberof TodoAdminData
     */
    created?: any;
}
