/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransactionData
 */
export interface TransactionData {
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    accountName?: any | null;
    /**
     * 
     * @type {AccountType}
     * @memberof TransactionData
     */
    accountType?: any;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof TransactionData
     */
    status?: any;
    /**
     * 
     * @type {number}
     * @memberof TransactionData
     */
    transactionDate?: any;
    /**
     * 
     * @type {number}
     * @memberof TransactionData
     */
    amount?: any;
    /**
     * 
     * @type {string}
     * @memberof TransactionData
     */
    description?: any | null;
}
