/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransactionSummary
 */
export interface TransactionSummary {
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    id?: any | null;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof TransactionSummary
     */
    status?: any;
    /**
     * 
     * @type {number}
     * @memberof TransactionSummary
     */
    value: any;
    /**
     * 
     * @type {string}
     * @memberof TransactionSummary
     */
    currency: any;
}
