/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateFinance
 */
export interface UpdateFinance {
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    monthlyEarnings?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    maritalStatus?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFinance
     */
    numKids?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    residenceType?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    nextOfKin?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    nextKinNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    locationState?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFinance
     */
    locationLGA?: any | null;
}
