/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateTodo
 */
export interface UpdateTodo {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodo
     */
    text?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTodo
     */
    active?: any;
    /**
     * 
     * @type {TodoCriteria}
     * @memberof UpdateTodo
     */
    criteria?: any;
}
