/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateProfile
 */
export interface UpdateProfile {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    token?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    firstName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    lastName?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfile
     */
    dob?: any;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    phoneNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfile
     */
    nickname?: any | null;
}
