/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpsertDailyRate
 */
export interface UpsertDailyRate {
    /**
     * 
     * @type {string}
     * @memberof UpsertDailyRate
     */
    investmentId?: any;
    /**
     * 
     * @type {number}
     * @memberof UpsertDailyRate
     */
    date?: any;
    /**
     * 
     * @type {number}
     * @memberof UpsertDailyRate
     */
    interest?: any;
}
