/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    firstName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    lastName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    email?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    currency?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    country?: any | null;
}
