/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerifiableAddress
 */
export interface VerifiableAddress {
    /**
     * 
     * @type {string}
     * @memberof VerifiableAddress
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof VerifiableAddress
     */
    status?: any | null;
    /**
     * 
     * @type {string}
     * @memberof VerifiableAddress
     */
    value?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof VerifiableAddress
     */
    verified?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof VerifiableAddress
     */
    verifiedAt?: any | null;
    /**
     * 
     * @type {string}
     * @memberof VerifiableAddress
     */
    via?: any | null;
}
