/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WebinarPostUpdateRequest
 */
export interface WebinarPostUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof WebinarPostUpdateRequest
     */
    title: any;
    /**
     * 
     * @type {string}
     * @memberof WebinarPostUpdateRequest
     */
    body: any;
    /**
     * 
     * @type {string}
     * @memberof WebinarPostUpdateRequest
     */
    videoUrl: any;
    /**
     * 
     * @type {number}
     * @memberof WebinarPostUpdateRequest
     */
    start: any;
    /**
     * 
     * @type {string}
     * @memberof WebinarPostUpdateRequest
     */
    category: any;
    /**
     * 
     * @type {boolean}
     * @memberof WebinarPostUpdateRequest
     */
    isFeatured: any;
    /**
     * 
     * @type {number}
     * @memberof WebinarPostUpdateRequest
     */
    minimumSavings?: any;
}
