/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WebinarPost
 */
export interface WebinarPost {
    /**
     * 
     * @type {string}
     * @memberof WebinarPost
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof WebinarPost
     */
    authorId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof WebinarPost
     */
    title?: any | null;
    /**
     * 
     * @type {string}
     * @memberof WebinarPost
     */
    body?: any | null;
    /**
     * 
     * @type {number}
     * @memberof WebinarPost
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof WebinarPost
     */
    start?: any;
    /**
     * 
     * @type {string}
     * @memberof WebinarPost
     */
    videoUrl?: any | null;
}
