/* tslint:disable */
/* eslint-disable */
/**
 * She Leads Africa API
 * She Leads Africa API. Combined endpoint of all services provided.
 *
 * OpenAPI spec version: v0
 * Contact: olpie101@github.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WithdrawalResponse
 */
export interface WithdrawalResponse {
    /**
     * 
     * @type {string}
     * @memberof WithdrawalResponse
     */
    accountId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalResponse
     */
    bankAccountId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalResponse
     */
    transactionId?: any | null;
    /**
     * 
     * @type {number}
     * @memberof WithdrawalResponse
     */
    value: any;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalResponse
     */
    currency: any;
}
